### ISSUE TITLE
can not get advanced configuration working.

### ISSUE THREAD

**Issue by ilihai** [yast/yast-ntp-client#91]
when i hit the "Advanced Configuration" button, Leap 42.3 tell me:

> Internal error. Please report a bug report with logs.
> 
> Run save_y2logs to get complete logs.
> 
> Details: undefined method 'emtpy?' for "":String
> 
> Caller: /usr/share/YaST2/include/ntp-client/widgets. rb:285: in 'complexButtonHandle'

**Comment by kobliha** [comment]
Hi, then, could you please report the bug in bugzilla.opensuse.org and attach YaST logs?

Thanks
Lukas

**Comment by ilihai** [comment]
sure : )

https://bugzilla.opensuse.org/show_bug.cgi?id=1051899

**Comment by kobliha** [comment]
Thanks for the report. We'll now handle that in Bugzilla.
